sudo: required
services:
  - docker
before_install:
  - docker build -t shakeelvictor/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run shakeelvictor/react-test npm test -- --coverage
after_success:
  - docker build -t shakeelvictor/multi-client ./client
  - docker build -t shakeelvictor/multi-nginx ./nginx
  - docker build -t shakeelvictor/multi-server ./server
  - docker build -t shakeelvictor/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shakeelvictor/multi-client
  - docker push shakeelvictor/multi-nginx
  - docker push shakeelvictor/multi-server
  - docker push shakeelvictor/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-933783733647
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
